(function() {
    'use strict';
  
    angular
    .module('core').config(["$translateProvider","appCONSTANTS",function($translateProvider,appCONSTANTS){
          
          var en_translations = {
              "Title":"Title",
              "Description":"Description",
              "Rate":"Rate",
              "Price":"Price",
              "Currency":"Currency",
              "IsMain":"Is Main",
              "Home":"Home",
              "AboutUs": "About Us",
              "Template":"Image",
              "NoHomeAvailable": "No Home Content Available",
              "NoTemplateAvailable":"No Image Available",
              "NewTemplateLbl":"Add Image",
              "deleteBtn":"Delete",
              "UploadImageBtn":"Upload image",
              "requiredErr":"Required Field",
              "saveChangesBtn":"Save changes",
              "DiscardBtn":"Discard",
              "AddBtn":"Add", 
              "deleteConfirmationLbl":"Delete Confirmation",
              "AddHomeLbl":"Add Home",
              "TextOnly":"Text Only",
              "PriceLengthError": "Price should be from 1:10 numbers",
              "NameLengthError": "Number of characters should be from 2:50 characters",
              "NameLengthError500": "Number of characters should be from 3:500 characters",
              "NameLengthError50":"Number of characters should be from 2:50 characters",
              "NameLengthError400":"Number of characters should be from 2:400 characters",
              "Currency": "Currency",
              "AddCurrencyLbl": "Add Currency",
              "Edit": "Edit",
              "UpdateCurencyLbl": "Update Currency",
              "UpdateHomeLbl": "Update Home",
              "Yes":"Yes",
              "No":"No",
              "Offers":"Offers",
              "OurTeams": "Our Team",
              "Hotels":"Hotels",
              "NoContactUsAvailable": "No Contact Us Content Available",
              "NoOfferAvailable":"No Offer Content Available",
              "Email":"Email",
              "Number":"Mobile number",
              "Location":"Location",
              "ContactUs":"Contact Us",
              "logoutBtn":"logout",
              "NoOurTeamAvailable":"No Our Team Content Available",
              "NoCurrencyAvailable": "No Currency Content Available",
              "AddOfferLbl": "Add Offer",
              "AddOurTeamLbl": "Add member",
              "SaveAndExitBtn": "Save",
              "NoHotelAvailable":"No Hotel Content Available",
              "AddHotelLbl":"Add Hotel",
              "AddContactUsLbl":"Add Contact",
              "OwnerEmail": "Owner's Email",
              "MobileNumberLbl":"Mobile number",
              "NoAboutUsAvailable":"No About Us Content Available",
              "AddAboutUsLbl":"Add About Us",
              "Header":"Header",
              "SubTitle":"Sub-Title",
              "TitleColored":"Colored Title",
              "BoldArticle":"Bold Article",
              "AddSuccess": "Added Successfully",
              "EditSuccess":"Edited Successfully",
              "deleteBtn":"Delete",
              "cancelBtn":"Cancel",
              "NameLengthError7":"Number of characters should be from 2:7 characters",
              "NameLengthError10":"Number of characters should be from 2:10 characters",
              "NameLengthError15":"Number of characters should be from 2:15 characters",
              "NameLengthError100800":"Number of characters should be from 100:800 characters",
              "UpdateAboutUsLbl":"Update About Us",
              "NameLengthError80":"Number of characters should be from 2:80 characters",
              "NameLengthError16":"Number of characters should be from 2:16 characters",
              "NameLengthError120":"Number of characters should be from 2:120 characters",
              "NameLengthError700":"Number of characters should be from 2:700 characters",
              "UpdateOurTeamLbl": "Edit member's data",
              "WhatsAppNumberLbl" : "WhatsApp Number",
              "FacebookLink":"Facebook Account URL",
              "GmailLink":"Google+ Account URL",
              "TwitterLink":"Twitter Account URL",
              "Sections":"Show/hide sections and icons",
              "ShowEmail":"Show Email",
              "ShowMobile":"Show Mobile",
              "ShowOwnerEmail":"Show Owner's Email",
              "ShowWhatsApp":"Show WhatsApp",
              "ShowFacebook":"Show Facebook icon",
              "ShowGmail":"Show Gmail icon",
              "ShowTwitter":"Show Twitter icon",
              "UpdateContactUsLbl":"Update Contact Us",
              "LinkOnly":"Link Only",

          }
          
          var ar_translations = {
              "Title":"عنوان",
              "Description":"التفاصيل",
              "Rate":"تقييم",
              "Price":"السعر",
              "Currency":"العملة",
              "IsMain":"اساسي؟",
              "Home":"الرئيسية",
              "AboutUs": "عنا",
              "Template":"صورة",
              "NoHomeAvailable": "لا يوجد محتوي للصفحة الرئيسية",
              "NoTemplateAvailable":"لا يوجد صورة متاحة",
              "NewTemplateLbl":"اضافة صورة",
              "deleteBtn":"حذف",
              "UploadImageBtn":"اختر صوره",
              "requiredErr":"حقل مطلوب",
              "saveChangesBtn":"حفظ",
              "DiscardBtn":"تجاهل",
              "AddBtn":"اضافه",
              "deleteConfirmationLbl":"تأكيد الحذف",
              "AddHomeLbl":"اضافة رئيسيه",
              "TextOnly":"حروف فقط",
              "PriceLengthError": "السعر يجب ان يكون من 1:10 ارقام",
              "NameLengthError": "عدد الحروف يجب ان يكون من 2:50 حرف",
              "NameLengthError500": "عدد الحروف يجب ان يكون من 3:500 حرف",
              "NameLengthError50":"عدد الحروف يجب ان يكون من 2:50 حرف",
              "NameLengthError400":"عدد الحروف يجب ان يكون من 2:400 حرف",
              "Currency": "العملة",
              "AddCurrencyLbl": "اضافة عملة",
              "Edit":"تعديل",
              "UpdateCurencyLbl": "تعديل العملة",
              "UpdateHomeLbl": "تعديل الرئيسيه",
              "Yes":"نعم",
              "No":"لا",
              "Offers": "عروض",
              "OurTeams":"فريقنا",
              "Hotels":"فنادق",
              "NoContactUsAvailable": "لا يوجد محتوي لصفحة التواصل",
              "Email":"البريد الالكتروني",
              "Number":"رقم الجوال",
              "Location":"الموقع الجغرافي",
              "ContactUs":"تواصل معنا",
              "logoutBtn":"الخروج",
              "NoOfferAvailable":"لا يوجد محتوي لصفحة العروض",
              "NoOurTeamAvailable":"لا يوجد محتوي لصفحة الفريق",
              "NoCurrencyAvailable": "لا يوجد محتوي لصفحة العملة",
              "AddOfferLbl": "اضافة عرض",
              "AddOurTeamLbl": "اضافة عضو",
              "SaveAndExitBtn": "حفظ",
              "NoHotelAvailable": "لا يوجد محتوي لصفحة الفنادق",
              "AddHotelLbl":"اضافة فندق",
              "AddContactUsLbl":"اضافة تواصل",
              "OwnerEmail": "ايميل المالك",
              "MobileNumberLbl":"رقم الجوال",
              "NoAboutUsAvailable":"لا يوجد محتوي لصفحة عنا",
              "AddAboutUsLbl":"اضافة عنا",
              "Header":"عنوان اخر",
              "SubTitle":"عنوان فرعي",
              "TitleColored":"عنوان ملون",
              "BoldArticle":"عنوان مميز",
              "AddSuccess": "تمت الاضافة بنجاح",
              "EditSuccess":"تم التعديل بنجاح",
              "deleteBtn":"حذف",
              "cancelBtn":"الغاء",
              "NameLengthError7":"عدد الحروف يجب ان يكون من 2:7 حرف",
              "NameLengthError10":"عدد الحروف يجب ان يكون من 2:10 حرف",
              "NameLengthError15":"عدد الحروف يجب ان يكون من 2:15 حرف",
              "NameLengthError100800":"عدد الحروف يجب ان يكون من 100:800 حرف",
              "UpdateAboutUsLbl": "تعديل عنا",
              "NameLengthError80": "عدد الحروف يجب ان يكون من 2:80 حرف",
              "NameLengthError16":"عدد الحروف يجب ان يكون من 2:16 حرف",
              "NameLengthError120":"عدد الحروف يجب ان يكون من 2:120 حرف",
              "NameLengthError700":"عدد الحروف يجب ان يكون من 2:700 حرف",
              "UpdateOurTeamLbl":"تعديل بيانات العضو",
              "WhatsAppNumberLbl" : "رقم الواتس",
              "FacebookLink":"عنوان حساب الفيس بوك",
              "GmailLink":"عنوان حساب جوجل+",
              "TwitterLink":"عنوان حساب تويتير",
              "Sections":"اظهار/اخفاء الأقسام و الايقونات",
              "ShowEmail":"اظهار البريد الالكتروني",
              "ShowMobile":"اظهار رقم الجوال",
              "ShowOwnerEmail":"اظهار البريد الاكتروني الخاص بالمالك",
              "ShowWhatsApp":"اظهار رقم الواتس اب",
              "ShowFacebook":"اظهار ايقونة الفيس بوك",
              "ShowGmail":"اظهار ايقونة جوجل",
              "ShowTwitter":"اظهار ايقونة تويتر",
              "UpdateContactUsLbl":"تعديل التواصل",
              "LinkOnly":"عنوان فقط",

          }
          
          $translateProvider.translations('en',en_translations);
          
          $translateProvider.translations('ar',ar_translations);
          
          $translateProvider.preferredLanguage(appCONSTANTS.defaultLanguage);
          
          }]);
  
  }());
  